name: 'PyEmblem'
runs-on: ubuntu-latest
description: 'Creates multiple badge descriptions to be used with shields.io/endpoint payload controls'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  control_payload:
    description: 'Your secret with the gist scope'
    required: true
  payload_type:
    description: 'The type of payload you are sending'
    required: true
runs:
  using: "composite"
  steps:
    - run: python main.py ${{ github.event.inputs.control_payload }} ${{ github.event.inputs.payload_type }}
      shell: bash
