name: 'PyEmblem'
runs-on: ubuntu-latest
description: 'Creates multiple badge descriptions to be used with shields.io/endpoint payload controls'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  payloads_file:
    description: 'The file name to read'
    required: true
  token:
    description: 'Your github token with gist scope'
    required: true
  gist_id:
    description: 'Your github token with gist scope'
    required: true
  commit_message:
    description: 'Your github token with gist scope'
    required: true
runs:
  using: "composite"
  steps:
    - id: runs
      run: |
        python -m pip install requests
        python ${{ github.action_path }}/main.py ${{ inputs.payloads_file }} ${{ inputs.token }} ${{ inputs.gist_id }} ${{ inputs.commit_message }} ${{ github.action_path }}
      shell: bash
