name: 'PyEmblem'
runs-on: ubuntu-latest
description: 'Creates multiple badge descriptions to be used with shields.io/endpoint payload controls'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  control_payload:
    description: 'Your secret with the gist scope'
    required: true
  payload_type:
    description: 'The type of payload you are sending'
    required: true
outputs:
  status:
    description: 'Error codes and runtime details'
    value:  ${{ steps.runs.outputs.codes }}
runs:
  using: "composite"
  steps:
    - id: runs
      run: |
        python -m pip install requests
        control_payload=${{ github.event.inputs.control_payload }}
        payload_type=${{ github.event.inputs.payload_type }}
        python ${{ github.action_path }}/main.py $control_payload $payload_type
      shell: bash
