name: 'PyEmblem'
runs-on: ubuntu-latest
description: 'Creates multiple badge descriptions to be used with shields.io/endpoint payload controls'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  control_payload:
    description: 'Your secret with the gist scope'
    required: true
  payload_type:
    description: 'The type of payload you are sending'
    required: true
outputs:
  status:
    description: 'Error codes and runtime details'
    value:  ${{ steps.runs.outputs.codes }}
runs:
  using: "composite"
  steps:
    - id: runs
      run: |
        python main.py ${{ github.event.inputs.control_payload }} ${{ github.event.inputs.payload_type }}
        echo "::set-output name=codes::$(echo $outs)"
      shell: bash
