name: 'PyEmblem'
description: 'Creates multiple badge descriptions to be used with shields.io/endpoint payload controls'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  control_payload:
    description: 'Your secret with the gist scope'
    required: true
  payload_type:
    description: 'The type of payload you are sending'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - uses: actions/setup-python@v2
        with:
            python-version: 3.8
    python main.py ${{ github.event.inputs.control_payload }} ${{ github.event.inputs.payload_type }}
